/**
*  R12 EBS 中查找发运行税率的方法  
*  version 0.01 pre
**/
SELECT T.INPUT_TAX_CLASSIFICATION_CODE, RATE.PERCENTAGE_RATE
  FROM ZX_LINES_DET_FACTORS T, ZX_RATES_B RATE
 WHERE T.TRX_ID = &PO_HEADER_ID
   AND T.TRX_LINE_ID = &LINE_LOCATION_ID
   AND T.LINE_LEVEL_ACTION NOT IN ('CANCEL', 'DISCARD', 'DELETE')
   AND T.TRX_LINE_ID > 0
   -- do not modify the following conditions!
   -- begin
   AND T.APPLICATION_ID = 201
   AND t.event_class_code = 'PO_PA'
   AND T.ENTITY_CODE = 'PURCHASE_ORDER'
   AND T.TRX_LEVEL_TYPE = 'SHIPMENT'
   -- end
   -- rate conditions
   AND T.INPUT_TAX_CLASSIFICATION_CODE = RATE.TAX_RATE_CODE
   AND RATE.RATE_TYPE_CODE = 'PERCENTAGE'
   AND TRUNC(SYSDATE) BETWEEN RATE.EFFECTIVE_FROM AND
       NVL(RATE.EFFECTIVE_TO, TRUNC(SYSDATE))
   AND ROWNUM = 1 -- 临时解决方法
;

-- RATE 
SELECT * FROM ZX_RATES_B RATE
 WHERE RATE.RATE_TYPE_CODE = 'PERCENTAGE'
   AND TRUNC(SYSDATE) BETWEEN RATE.EFFECTIVE_FROM AND
       NVL(RATE.EFFECTIVE_TO, TRUNC(SYSDATE))
;
