SELECT OBJ.OWNER, OBJ.OBJECT_ID, OBJ.OBJECT_TYPE,
       LCK.ADDR, LCK.KADDR, LCK.SID, LCK.LMODE
  FROM DBA_OBJECTS OBJ, V$LOCK LCK
 WHERE OBJ.OBJECT_NAME='HCM_FOCUS_PLANNING_TEMP' 
   AND OBJ.OBJECT_TYPE ='TABLE'
   AND OBJ.OBJECT_ID = LCK.ID1
