-- 查询所表记录，并生成kill session语句
SELECT A.OBJECT_NAME, a.OBJECT_TYPE, V.LOCKED_MODE,
       S.STATUS SESSION_STATUS,
       S.MACHINE, S.MODULE, S.PROGRAM, S.ACTION, NVL(S.CLIENT_IDENTIFIER, S.OSUSER) "USER",
       SA.SQL_TEXT,
       'ALTER SYSTEM KILL SESSION ''' || S.SID || ',' || S.SERIAL# || '''' STMT
  FROM ALL_OBJECTS A, GV$LOCKED_OBJECT V, GV$SESSION S, GV$SQLAREA SA
 WHERE A.OBJECT_ID = V.OBJECT_ID
   AND V.SESSION_ID = S.SID
   AND S.SQL_ADDRESS = SA.ADDRESS (+)
   AND A.OBJECT_NAME = '&LOCKED_TABLE_NAME'
 ORDER BY S.sid, s.serial#;
