-- 查找性能最差的SQL
SELECT B.USERNAME USERNAME,
       A.DISK_READS READS,
       A.EXECUTIONS EXEC,
       A.DISK_READS / DECODE(A.EXECUTIONS, 0, 1, A.EXECUTIONS) RDS_EXEC_RATIO,
       A.SQL_TEXT STATEMENT
  FROM V$SQLAREA A, DBA_USERS B
 WHERE A.PARSING_USER_ID = B.USER_ID
   AND A.DISK_READS > 100000
 ORDER BY A.DISK_READS DESC;
;
