SELECT A.REQUEST_ID, D.SID, D.SERIAL#, D.OSUSER, D.PROCESS, C.SPID
  FROM APPS.FND_CONCURRENT_REQUESTS  A,
       APPS.FND_CONCURRENT_PROCESSES B,
       V$PROCESS                     C,
       V$SESSION                     D
 WHERE A.CONTROLLING_MANAGER = B.CONCURRENT_PROCESS_ID
   AND C.PID = B.ORACLE_PROCESS_ID
   AND B.SESSION_ID = D.AUDSID
   AND A.REQUEST_ID = &REQUEST_ID
 --  AND A.PHASE_CODE = 'R';
