SELECT *
  FROM (SELECT B.BUG_NUMBER, B.CREATION_DATE, 'BUG' PATCH_TYPE
          FROM APPS.AD_BUGS B
        UNION ALL
        SELECT P.PATCH_NAME, P.CREATION_DATE, 'PATCH'
          FROM APPS.AD_APPLIED_PATCHES P) T1
/*(SELECT trim('12689818') bug_number FROM dual) t2*/
 WHERE T1.BUG_NUMBER IN ('13728376', '9908378', '8728439');
