--
-- This sql script search all responsibilities that have access
-- to specified concurrent program.
--
SELECT RSP.RESPONSIBILITY_NAME
  FROM FND_RESPONSIBILITY_VL      RSP,
       FND_REQUEST_GROUPS         GRP,
       FND_REQUEST_GROUP_UNITS    UNT,
       FND_CONCURRENT_PROGRAMS_VL PRG
 WHERE RSP.REQUEST_GROUP_ID = GRP.REQUEST_GROUP_ID
   AND GRP.REQUEST_GROUP_ID = UNT.REQUEST_GROUP_ID
   AND GRP.APPLICATION_ID = UNT.APPLICATION_ID
   AND ( ( UNT.REQUEST_UNIT_ID = PRG.CONCURRENT_PROGRAM_ID AND UNT.REQUEST_UNIT_TYPE = 'P') OR 
         ( UNT.REQUEST_UNIT_ID = PRG.APPLICATION_ID AND UNT.REQUEST_UNIT_TYPE = 'A' ) )
   AND PRG.CONCURRENT_PROGRAM_NAME = '&CONC_PROGRAM'
UNION ALL
-- Add requet set support
SELECT RSP.RESPONSIBILITY_NAME
  FROM FND_RESPONSIBILITY_VL      RSP,
       FND_REQUEST_GROUPS         GRP,
       FND_REQUEST_GROUP_UNITS    UNT,
       FND_REQUEST_SETS           FRS
 WHERE RSP.REQUEST_GROUP_ID = GRP.REQUEST_GROUP_ID
   AND GRP.REQUEST_GROUP_ID = UNT.REQUEST_GROUP_ID
   AND GRP.APPLICATION_ID = UNT.APPLICATION_ID
   AND UNT.REQUEST_UNIT_TYPE = 'S'
   AND UNT.REQUEST_UNIT_ID = FRS.REQUEST_SET_ID
   AND FRS.REQUEST_SET_NAME = '&CONC_PROGRAM'
;
